sudo: required
services: docker
language: bash
env:
    - VERSION=2.8.4
branches:
  only:
    - master
before_script:
    - sudo apt-get install jq
    - wget -N http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_2.8+dfsg-4+b2_amd64.deb
    - sudo dpkg -i qemu-user-static_2.8+dfsg-4+b2_amd64.deb
script:
    - sudo ./publish.sh -v "$VERSION" -t "$GITHUB_TOKEN"
    - sudo ./update.sh -v "$VERSION"
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push multiarch/qemu-user-static; fi