sudo: required
services: docker
language: bash
env:
    global:
        - VERSION=2.9.1
        - REPO=multiarch/qemu-user-static
branches:
  only:
    - master
before_script:
    - sudo apt-get install jq rpm2cpio cpio
    - wget --content-disposition https://kojipkgs.fedoraproject.org/packages/qemu/2.9.0/1.fc27/x86_64/qemu-user-static-2.9.0-1.fc27.x86_64.rpm
    - sudo rpm2cpio qemu-user-static-2.9.0-1.fc27.x86_64.rpm | cpio -dimv
script:
    - sudo ./publish.sh -v "$VERSION" -t "$GITHUB_TOKEN" -r "$REPO"
    - sudo ./update.sh -v "$VERSION" -r "$REPO"
after_success:
    - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $REPO; fi